<?php

namespace App\Http\Controllers;

use Inertia\Inertia;
use Inertia\Response;

class StorefrontController extends Controller
{
    public function index(): Response
    {
        return Inertia::render('products/index', [
            'products' => $this->products(),
            'filters' => [
                'brands' => ['Tifoo', 'Goldanalytix', 'Tobolin'],
                'categories' => [
                    'Tifoo' => ['Galvanisieren', 'Eloxieren', 'Brünieren', 'Stromlos Beschichten', 'Vor- & Nachbehandlung', 'Patinieren', 'Sonstiges'],
                    'Goldanalytix' => ['Für Schmuck', 'Für Münzen', 'Für Barren'],
                    'Tobolin' => ['Horizontalsperre', 'Innenabdichtung', 'Feuchtemessung', 'Pflasterpflege', 'Zubehör'],
                ],
            ],
        ]);
    }

    public function show(string $product): Response
    {
        $selectedProduct = collect($this->products())
            ->firstWhere('slug', $product);

        abort_if($selectedProduct === null, 404);

        $similarProducts = collect($this->products())
            ->reject(fn (array $item): bool => $item['slug'] === $product)
            ->filter(fn (array $item): bool => $item['brand'] === $selectedProduct['brand'] || $item['category'] === $selectedProduct['category']);

        $fallbackProducts = collect($this->products())
            ->reject(fn (array $item): bool => $item['slug'] === $product)
            ->reject(fn (array $item): bool => $similarProducts->contains('slug', $item['slug']));

        return Inertia::render('products/show', [
            'product' => $selectedProduct,
            'similarProducts' => $similarProducts
                ->concat($fallbackProducts)
                ->take(4)
                ->values()
                ->all(),
        ]);
    }

    public function cart(): Response
    {
        return Inertia::render('cart');
    }

    /**
     * @return array<int, array{
     *     slug: string,
     *     name: string,
     *     brand: string,
     *     category: string,
     *     price: string,
     *     priceCents: int,
     *     image: string,
     *     productNumber?: string,
     *     deliveryTime?: string,
     *     badge: string,
     *     excerpt: string,
     *     description: string,
     *     descriptionBody?: array<int, string>,
     *     highlights: array<int, string>,
     *     scopeOfDelivery?: array<int, string>,
     *     downloads?: array<int, string>,
     *     safetyInfo?: array<int, string>,
     *     manufacturer?: array{name: string, address: array<int, string>, phone: string, email: string},
     *     reviewNote?: string,
     *     specifications: array<string, string>
     * }>
     */
    private function products(): array
    {
        return [
            [
                'slug' => 'titandraht-0-5mm-1-meter',
                'name' => 'Titandraht 0.5mm, 1 Meter',
                'brand' => 'Tifoo',
                'category' => 'Galvanisieren',
                'price' => '3,90 €',
                'priceCents' => 390,
                'image' => 'https://www.tifoo.de/media/12/e7/06/1714735409/08-12-00011-titandraht-0-5mm-1-meter-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Galvanisieren',
                'excerpt' => 'Selbst vergolden, versilbern und beschichten mit Stift-, Bad- oder Tampongalvanik.',
                'description' => 'Titandraht 0.5mm, 1 Meter – Originalprodukt aus dem Tifoo-Shopbereich „Galvanisieren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Galvanisieren', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Galvanisieren',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'e-zinc-full-set',
                'name' => 'E-Zinc - Full set',
                'brand' => 'Tifoo',
                'category' => 'Galvanisieren',
                'price' => '153,90 €',
                'priceCents' => 15390,
                'image' => 'https://www.tifoo.de/media/08/4c/b6/1691437808/01-89-00000-e-re-zink-stift-galvanik-elektrolyt-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Galvanisieren',
                'excerpt' => 'Selbst vergolden, versilbern und beschichten mit Stift-, Bad- oder Tampongalvanik.',
                'description' => 'E-Zinc - Full set – Originalprodukt aus dem Tifoo-Shopbereich „Galvanisieren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Galvanisieren', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Galvanisieren',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'carbon-graphite-rod-anode-8-mm',
                'name' => 'Carbon / Graphite rod anode (Ø 8 mm)',
                'brand' => 'Tifoo',
                'category' => 'Galvanisieren',
                'price' => '9,90 €',
                'priceCents' => 990,
                'image' => 'https://www.tifoo.de/media/b1/3a/f3/1691437806/01-40-00000-graphitstab-anode-graphitanode-graphitelektrode-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Galvanisieren',
                'excerpt' => 'Selbst vergolden, versilbern und beschichten mit Stift-, Bad- oder Tampongalvanik.',
                'description' => 'Carbon / Graphite rod anode (Ø 8 mm) – Originalprodukt aus dem Tifoo-Shopbereich „Galvanisieren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Galvanisieren', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Galvanisieren',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'pp-tank-large-6-litres',
                'name' => 'PP Tank large (6 litres)',
                'brand' => 'Tifoo',
                'category' => 'Eloxieren',
                'price' => '14,50 €',
                'priceCents' => 1450,
                'image' => 'https://www.tifoo.de/media/ee/39/5e/1691437808/01-78-00000-bad-galvanik-wanne-29x20x15-cm-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Eloxieren',
                'excerpt' => 'Aluminiumteile eloxieren, einfärben und dauerhaft schützen.',
                'description' => 'PP Tank large (6 litres) – Originalprodukt aus dem Tifoo-Shopbereich „Eloxieren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Eloxieren', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Eloxieren',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'anodising-kit-deluxe',
                'name' => 'Anodising Kit "Deluxe"',
                'brand' => 'Tifoo',
                'category' => 'Eloxieren',
                'price' => '293,90 €',
                'priceCents' => 29390,
                'image' => 'https://www.tifoo.de/media/9d/b3/76/1692956961/int-produktbild-08-12-00003.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Eloxieren',
                'excerpt' => 'Aluminiumteile eloxieren, einfärben und dauerhaft schützen.',
                'description' => 'Anodising Kit "Deluxe" – Originalprodukt aus dem Tifoo-Shopbereich „Eloxieren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Eloxieren', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Eloxieren',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'anodising-kit-starter-kit',
                'name' => 'Anodising Kit starter kit',
                'brand' => 'Tifoo',
                'category' => 'Eloxieren',
                'price' => '99,90 €',
                'priceCents' => 9990,
                'image' => 'https://www.tifoo.de/media/28/56/cd/1691431667/08-12-00000-eloxal-starterset-tifoo-anodisieren-diy-anodizing-kit-anodizado-casero-anodisation-maison-set-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Eloxieren',
                'excerpt' => 'Aluminiumteile eloxieren, einfärben und dauerhaft schützen.',
                'description' => 'Anodising Kit starter kit – Originalprodukt aus dem Tifoo-Shopbereich „Eloxieren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Eloxieren', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Eloxieren',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'bluing-solution-set-black-devil',
                'name' => 'Bluing solution set "Black Devil"',
                'brand' => 'Tifoo',
                'category' => 'Brünieren',
                'price' => '44,90 €',
                'priceCents' => 4490,
                'image' => 'https://www.tifoo.de/media/bc/1f/45/1711541476/int-produktfoto-set-ohne-eimer-02-23-00250.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Brünieren',
                'excerpt' => 'Stahl und Eisen schwärzen und vor Korrosion schützen.',
                'description' => 'Bluing solution set "Black Devil" – Originalprodukt aus dem Tifoo-Shopbereich „Brünieren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Brünieren', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Brünieren',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'edelstahl-brunierung-250-ml',
                'name' => 'Edelstahl-Brünierung 250 ml',
                'brand' => 'Tifoo',
                'category' => 'Brünieren',
                'price' => '24,90 €',
                'priceCents' => 2490,
                'image' => 'https://www.tifoo.de/media/d6/47/d8/1710251997/int-produktbild-02-63.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Brünieren',
                'excerpt' => 'Stahl und Eisen schwärzen und vor Korrosion schützen.',
                'description' => 'Edelstahl-Brünierung 250 ml – Originalprodukt aus dem Tifoo-Shopbereich „Brünieren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Brünieren', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Brünieren',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'quick-bluing-solution-black-magic',
                'name' => 'Quick bluing solution "Black Magic"',
                'brand' => 'Tifoo',
                'category' => 'Brünieren',
                'price' => '11,20 €',
                'priceCents' => 1120,
                'image' => 'https://www.tifoo.de/media/80/8a/dd/1691437810/02-21-00050-tifoo-schnellbruenierung-50-ml-waffe-bruenieren-streichbruenierung-kaltbruenierung-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Brünieren',
                'excerpt' => 'Stahl und Eisen schwärzen und vor Korrosion schützen.',
                'description' => 'Quick bluing solution "Black Magic" – Originalprodukt aus dem Tifoo-Shopbereich „Brünieren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Brünieren', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Brünieren',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'gold-leaf-adhesive-and-clear-lacquer-for-gold-leaf-and-metal-leaf-2-x-500-ml',
                'name' => 'Gold leaf adhesive and clear lacquer for gold leaf and metal leaf (2 x 500 ml)',
                'brand' => 'Tifoo',
                'category' => 'Stromlos Beschichten',
                'price' => '39,90 €',
                'priceCents' => 3990,
                'image' => 'https://www.tifoo.de/media/20/76/31/1737619073/int-produktbild-04-03.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Stromlos Beschichten',
                'excerpt' => 'Oberflächen veredeln und beschichten – ganz ohne Strom.',
                'description' => 'Gold leaf adhesive and clear lacquer for gold leaf and metal leaf (2 x 500 ml) – Originalprodukt aus dem Tifoo-Shopbereich „Stromlos Beschichten“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Stromlos Beschichten', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Stromlos Beschichten',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'blue-chromate-conversion-coating',
                'name' => 'Blue chromate conversion coating',
                'brand' => 'Tifoo',
                'category' => 'Stromlos Beschichten',
                'price' => '32,90 €',
                'priceCents' => 3290,
                'image' => 'https://www.tifoo.de/media/d5/db/3f/1691437807/01-44-01000-blauchromatierung-verzinken-zinkelektrolyt-gelbchromatierung-chromatierung-116542.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Stromlos Beschichten',
                'excerpt' => 'Oberflächen veredeln und beschichten – ganz ohne Strom.',
                'description' => 'Blue chromate conversion coating – Originalprodukt aus dem Tifoo-Shopbereich „Stromlos Beschichten“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Stromlos Beschichten', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Stromlos Beschichten',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'glow-in-the-dark-powder-blue',
                'name' => 'Glow in the dark powder blue',
                'brand' => 'Tifoo',
                'category' => 'Stromlos Beschichten',
                'price' => '14,90 €',
                'priceCents' => 1490,
                'image' => 'https://www.tifoo.de/media/ae/a4/e2/1691437809/04-08-00050-nachleuchtfarbe-gluehpulver-leuchtpulver-leuchtpigment-glow-in-the-dark-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Stromlos Beschichten',
                'excerpt' => 'Oberflächen veredeln und beschichten – ganz ohne Strom.',
                'description' => 'Glow in the dark powder blue – Originalprodukt aus dem Tifoo-Shopbereich „Stromlos Beschichten“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Stromlos Beschichten', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Stromlos Beschichten',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'galvano-activator-1000-ml',
                'name' => 'Galvano activator (1000 ml)',
                'brand' => 'Tifoo',
                'category' => 'Vor- & Nachbehandlung',
                'price' => '19,90 €',
                'priceCents' => 1990,
                'image' => 'https://www.tifoo.de/media/12/72/fe/1711540372/int-produktfoto-02-25-01000.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Vor- & Nachbehandlung',
                'excerpt' => 'Oberflächen reinigen, aktivieren und nachbehandeln.',
                'description' => 'Galvano activator (1000 ml) – Originalprodukt aus dem Tifoo-Shopbereich „Vor- & Nachbehandlung“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Vor- & Nachbehandlung', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Vor- & Nachbehandlung',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'copper-and-brass-cleaner',
                'name' => 'Copper and brass cleaner',
                'brand' => 'Tifoo',
                'category' => 'Vor- & Nachbehandlung',
                'price' => '16,90 €',
                'priceCents' => 1690,
                'image' => 'https://www.tifoo.de/media/3c/9f/d3/1706599706/int-produktbild-03-02-01000.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Vor- & Nachbehandlung',
                'excerpt' => 'Oberflächen reinigen, aktivieren und nachbehandeln.',
                'description' => 'Copper and brass cleaner – Originalprodukt aus dem Tifoo-Shopbereich „Vor- & Nachbehandlung“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Vor- & Nachbehandlung', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Vor- & Nachbehandlung',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'degreaser',
                'name' => 'Degreaser',
                'brand' => 'Tifoo',
                'category' => 'Vor- & Nachbehandlung',
                'price' => '19,90 €',
                'priceCents' => 1990,
                'image' => 'https://www.tifoo.de/media/f4/90/2c/1714120275/int-produktfoto-01-37-01000.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Vor- & Nachbehandlung',
                'excerpt' => 'Oberflächen reinigen, aktivieren und nachbehandeln.',
                'description' => 'Degreaser – Originalprodukt aus dem Tifoo-Shopbereich „Vor- & Nachbehandlung“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Vor- & Nachbehandlung', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Vor- & Nachbehandlung',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'patination-fluid-copper-brass-ager',
                'name' => 'Patination Fluid - Copper & Brass Ager',
                'brand' => 'Tifoo',
                'category' => 'Patinieren',
                'price' => '23,90 €',
                'priceCents' => 2390,
                'image' => 'https://www.tifoo.de/media/d6/d0/83/1711540607/02-17-00250-patinieren-beize-patinierung-metall-beizung-antiquieren-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Patinieren',
                'excerpt' => 'Buntmetalle künstlich altern und patinieren.',
                'description' => 'Patination Fluid - Copper & Brass Ager – Originalprodukt aus dem Tifoo-Shopbereich „Patinieren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Patinieren', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Patinieren',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'silver-patination-20-ml',
                'name' => 'Silver patination (20 ml)',
                'brand' => 'Tifoo',
                'category' => 'Patinieren',
                'price' => '19,90 €',
                'priceCents' => 1990,
                'image' => 'https://www.tifoo.de/media/e9/45/3f/1691437808/02-19-00020-silber-patinieren-patinierung-schwaerzen-beizen-patina-oxidation-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Patinieren',
                'excerpt' => 'Buntmetalle künstlich altern und patinieren.',
                'description' => 'Silver patination (20 ml) – Originalprodukt aus dem Tifoo-Shopbereich „Patinieren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Patinieren', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Patinieren',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'bronze-paint-100-ml',
                'name' => 'Bronze paint (100 ml)',
                'brand' => 'Tifoo',
                'category' => 'Patinieren',
                'price' => '19,90 €',
                'priceCents' => 1990,
                'image' => 'https://www.tifoo.de/media/20/d8/d4/1691437810/02-51-00100-acryl-farbe-bronze-metallic-patinierung-vintage-deko-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Patinieren',
                'excerpt' => 'Buntmetalle künstlich altern und patinieren.',
                'description' => 'Bronze paint (100 ml) – Originalprodukt aus dem Tifoo-Shopbereich „Patinieren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Patinieren', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Patinieren',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'gold-silver-and-platinum-testing-kit',
                'name' => 'Gold, silver and platinum testing kit',
                'brand' => 'Tifoo',
                'category' => 'Sonstiges',
                'price' => '67,90 €',
                'priceCents' => 6790,
                'image' => 'https://www.tifoo.de/media/6f/47/e1/1691437811/06-04-00000-gold-test-silber-test-platin-test-tester-testsaeuren-testloesungen-pruefsaeuren-pruefloesungen-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Sonstiges',
                'excerpt' => 'Weitere Produkte aus dem Tifoo-Shop.',
                'description' => 'Gold, silver and platinum testing kit – Originalprodukt aus dem Tifoo-Shopbereich „Sonstiges“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Sonstiges', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Sonstiges',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'gold-testing-kit',
                'name' => 'Gold testing kit',
                'brand' => 'Tifoo',
                'category' => 'Sonstiges',
                'price' => '35,90 €',
                'priceCents' => 3590,
                'image' => 'https://www.tifoo.de/media/55/1c/4b/1691437809/06-17-00000-goldpruefset-tester-set-gold-altgold-testen-pruefsaeuren-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Sonstiges',
                'excerpt' => 'Weitere Produkte aus dem Tifoo-Shop.',
                'description' => 'Gold testing kit – Originalprodukt aus dem Tifoo-Shopbereich „Sonstiges“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Sonstiges', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Sonstiges',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'silver-testing-kit',
                'name' => 'Silver testing kit',
                'brand' => 'Tifoo',
                'category' => 'Sonstiges',
                'price' => '25,90 €',
                'priceCents' => 2590,
                'image' => 'https://www.tifoo.de/media/c1/3e/b2/1739185103/int_produktbild-1_06-03.png',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Sonstiges',
                'excerpt' => 'Weitere Produkte aus dem Tifoo-Shop.',
                'description' => 'Silver testing kit – Originalprodukt aus dem Tifoo-Shopbereich „Sonstiges“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Sonstiges', 'Marke Tifoo', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Sonstiges',
                    'Marke' => 'Tifoo',
                ],
            ],
            [
                'slug' => 'caratscreenpen-v2',
                'name' => 'CaratScreenPen V2',
                'brand' => 'Goldanalytix',
                'category' => 'Für Schmuck',
                'price' => '945,00 €',
                'priceCents' => 94500,
                'image' => 'https://www.gold-analytix.de/media/2e/d9/33/1780981998/int-produktbild-g-01-0012-001vergrert.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Für Schmuck',
                'excerpt' => 'Echtheitsprüfung und Goldgehaltsbestimmung für Schmuck.',
                'description' => 'CaratScreenPen V2 – Originalprodukt aus dem Goldanalytix-Shopbereich „Für Schmuck“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Für Schmuck', 'Marke Goldanalytix', 'Live-Shopdaten als Platzhalter angebunden'],
                'descriptionBody' => [
                    'Would you like to know how much the family gold jewellery is really worth? Are you sure that your wedding ring is really made of 14 carat gold? The CaratScreenPen is a proven testing device for reliably checking the authenticity of gold jewellery of all shapes and colours.',
                    'The sophisticated electrochemical measuring system makes it possible to determine the fineness of almost any item containing gold. Objects made of platinum or palladium as well as rhodium-plated jewellery can also be identified.',
                    'The CaratScreenPen is suitable for commercial and private users: metal dealers, antique markets, pawn shops, private gold purchases and anyone who wants to protect themselves from counterfeits.',
                    'Please note: the CaratScreenPen is not suitable for testing silver jewellery and is based on a purely superficial measurement. For further information, please refer to the instruction manual.',
                    'The perfect solution when buying and selling gold jewellery: use the CaratScreenPen for more security during evaluation and purchase conversations.',
                ],
                'scopeOfDelivery' => [
                    'CaratScreenPen',
                    'Measuring pen V2 (consumable item)',
                    'Jack cable',
                    'USB-C charger',
                    'Glass fibre pen',
                    'File',
                    'Detailed instruction manual',
                    'Practical, padded carrying case',
                    'Shipping carton',
                ],
                'downloads' => [
                    'Instruction Manual CaratScreenPen V2',
                    'Application information for CaratScreenPen V2',
                    'Product safety information',
                    'Shipping and returns information',
                ],
                'safetyInfo' => [
                    'The information on the product label must always be followed.',
                    'The measuring pen is a consumable item and must be replaced with the compatible V2 replacement pen.',
                    'The measurement is a surface measurement; in case of doubt, additional testing methods are recommended.',
                ],
                'manufacturer' => [
                    'name' => 'MARAWE GmbH & Co. KG',
                    'address' => ['An d. Irler Höhe 3B', '93055 Regensburg, Deutschland'],
                    'phone' => '+49 941 29020439',
                    'email' => 'info@marawe.de',
                ],
                'reviewNote' => 'No reviews found yet. Product review submission is reserved for logged-in customers.',
                'specifications' => [
                    'Kategorie' => 'Für Schmuck',
                    'Marke' => 'Goldanalytix',
                ],
            ],
            [
                'slug' => 'ersatz-messstift-v2-fur-caratscreenpen-v2',
                'name' => 'Ersatz-Messstift V2 für CaratScreenPen V2',
                'brand' => 'Goldanalytix',
                'category' => 'Für Schmuck',
                'price' => '39,90 €',
                'priceCents' => 3990,
                'image' => 'https://www.gold-analytix.de/media/74/a9/2b/1770904843/g-01-0012-p-v2-ersatz-messstift-v2-caratscreenpen-2.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Für Schmuck',
                'excerpt' => 'Echtheitsprüfung und Goldgehaltsbestimmung für Schmuck.',
                'description' => 'Ersatz-Messstift V2 für CaratScreenPen V2 – Originalprodukt aus dem Goldanalytix-Shopbereich „Für Schmuck“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Für Schmuck', 'Marke Goldanalytix', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Für Schmuck',
                    'Marke' => 'Goldanalytix',
                ],
            ],
            [
                'slug' => 'prufsaureset-gold-silber-und-platin',
                'name' => 'Prüfsäureset "Gold, Silber und Platin"',
                'brand' => 'Goldanalytix',
                'category' => 'Für Schmuck',
                'price' => '67,90 €',
                'priceCents' => 6790,
                'image' => 'https://www.gold-analytix.de/media/6f/47/e1/1691437811/06-04-00000-gold-test-silber-test-platin-test-tester-testsaeuren-testloesungen-pruefsaeuren-pruefloesungen-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Für Schmuck',
                'excerpt' => 'Echtheitsprüfung und Goldgehaltsbestimmung für Schmuck.',
                'description' => 'Prüfsäureset "Gold, Silber und Platin" – Originalprodukt aus dem Goldanalytix-Shopbereich „Für Schmuck“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Für Schmuck', 'Marke Goldanalytix', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Für Schmuck',
                    'Marke' => 'Goldanalytix',
                ],
            ],
            [
                'slug' => 'goldscreensensor',
                'name' => 'GoldScreenSensor',
                'brand' => 'Goldanalytix',
                'category' => 'Für Münzen',
                'price' => '895,00 €',
                'priceCents' => 89500,
                'image' => 'https://www.gold-analytix.de/media/7c/79/ca/1780982621/en-produktbild-g-01-0013-003vergrert.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Für Münzen',
                'excerpt' => 'Zerstörungsfreie Echtheitsprüfung für Anlagemünzen.',
                'description' => 'GoldScreenSensor – Originalprodukt aus dem Goldanalytix-Shopbereich „Für Münzen“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Für Münzen', 'Marke Goldanalytix', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Für Münzen',
                    'Marke' => 'Goldanalytix',
                ],
            ],
            [
                'slug' => 'goldscreenpen',
                'name' => 'GoldScreenPen',
                'brand' => 'Goldanalytix',
                'category' => 'Für Münzen',
                'price' => '1.190,00 €',
                'priceCents' => 119000,
                'image' => 'https://www.gold-analytix.de/media/7d/93/c2/1755592145/en-anwendungsbild-gold-maple-leaf-fake-g-01-0018.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Für Münzen',
                'excerpt' => 'Zerstörungsfreie Echtheitsprüfung für Anlagemünzen.',
                'description' => 'GoldScreenPen – Originalprodukt aus dem Goldanalytix-Shopbereich „Für Münzen“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Für Münzen', 'Marke Goldanalytix', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Für Münzen',
                    'Marke' => 'Goldanalytix',
                ],
            ],
            [
                'slug' => 'prazisionswaage',
                'name' => 'Präzisionswaage',
                'brand' => 'Goldanalytix',
                'category' => 'Für Münzen',
                'price' => '19,90 €',
                'priceCents' => 1990,
                'image' => 'https://www.gold-analytix.de/media/d0/8a/0c/1691437821/g-01-0015-praezisionswaage-goldanalytix-gold-testen-muenzen-echtheit-pruefen-abmessung-juwelierswaage-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Für Münzen',
                'excerpt' => 'Zerstörungsfreie Echtheitsprüfung für Anlagemünzen.',
                'description' => 'Präzisionswaage – Originalprodukt aus dem Goldanalytix-Shopbereich „Für Münzen“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Für Münzen', 'Marke Goldanalytix', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Für Münzen',
                    'Marke' => 'Goldanalytix',
                ],
            ],
            [
                'slug' => 'barscreensensor-ultraschallanalysegerat',
                'name' => 'BarScreenSensor - Ultraschallanalysegerät',
                'brand' => 'Goldanalytix',
                'category' => 'Für Barren',
                'price' => '445,00 €',
                'priceCents' => 44500,
                'image' => 'https://www.gold-analytix.de/media/50/57/2a/1691437811/g-01-0010-barscreensensor-ultraschallgeraet-gold-tester-barren-echtheit-pruefen-goldpruefgeraet-edel-metall-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Für Barren',
                'excerpt' => 'Zerstörungsfreie Echtheitsprüfung für Barren.',
                'description' => 'BarScreenSensor - Ultraschallanalysegerät – Originalprodukt aus dem Goldanalytix-Shopbereich „Für Barren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Für Barren', 'Marke Goldanalytix', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Für Barren',
                    'Marke' => 'Goldanalytix',
                ],
            ],
            [
                'slug' => 'ersatzflasche-ultraschallgel-fur-barscreensensor-100-ml',
                'name' => 'Ersatzflasche Ultraschallgel für BarScreenSensor (100 mL)',
                'brand' => 'Goldanalytix',
                'category' => 'Für Barren',
                'price' => '9,90 €',
                'priceCents' => 990,
                'image' => 'https://www.gold-analytix.de/media/ac/24/18/1755595688/g-z-0027-ultraschallgel-100ml-ersatzflasche-barscreensensor-2.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Für Barren',
                'excerpt' => 'Zerstörungsfreie Echtheitsprüfung für Barren.',
                'description' => 'Ersatzflasche Ultraschallgel für BarScreenSensor (100 mL) – Originalprodukt aus dem Goldanalytix-Shopbereich „Für Barren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Für Barren', 'Marke Goldanalytix', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Für Barren',
                    'Marke' => 'Goldanalytix',
                ],
            ],
            [
                'slug' => 'magnetwaage-magneticscreenscale',
                'name' => 'Magnetwaage - MagneticScreenScale',
                'brand' => 'Goldanalytix',
                'category' => 'Für Barren',
                'price' => '945,00 €',
                'priceCents' => 94500,
                'image' => 'https://www.gold-analytix.de/media/a9/dd/de/1691437810/g-01-0002-magnetwaage-gold-testen-wolfram-zerstoerungsfrei-echtheitspruefung-edelmetalle-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Für Barren',
                'excerpt' => 'Zerstörungsfreie Echtheitsprüfung für Barren.',
                'description' => 'Magnetwaage - MagneticScreenScale – Originalprodukt aus dem Goldanalytix-Shopbereich „Für Barren“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Für Barren', 'Marke Goldanalytix', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Für Barren',
                    'Marke' => 'Goldanalytix',
                ],
            ],
            [
                'slug' => 'horizontalsperre-tobostick-set',
                'name' => 'Horizontalsperre Tobostick Set',
                'brand' => 'Tobolin',
                'category' => 'Horizontalsperre',
                'price' => '19,99 €',
                'priceCents' => 1999,
                'image' => 'https://www.tobolin.de/media/37/f9/b6/1754463948/int-produktbild-24er-set-12-saugwinkel-freigestellt-03-07-12003.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Horizontalsperre',
                'excerpt' => 'Schutz gegen kapillar aufsteigende Feuchtigkeit im Mauerwerk.',
                'description' => 'Horizontalsperre Tobostick Set – Originalprodukt aus dem Tobolin-Shopbereich „Horizontalsperre“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Horizontalsperre', 'Marke Tobolin', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Horizontalsperre',
                    'Marke' => 'Tobolin',
                ],
            ],
            [
                'slug' => 'horizontalsperre-set',
                'name' => 'Horizontalsperre-Set',
                'brand' => 'Tobolin',
                'category' => 'Horizontalsperre',
                'price' => '15,83 €',
                'priceCents' => 1583,
                'image' => 'https://www.tobolin.de/media/04/d8/d4/1754463743/int-produktbild-03-07-12000.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Horizontalsperre',
                'excerpt' => 'Schutz gegen kapillar aufsteigende Feuchtigkeit im Mauerwerk.',
                'description' => 'Horizontalsperre-Set – Originalprodukt aus dem Tobolin-Shopbereich „Horizontalsperre“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Horizontalsperre', 'Marke Tobolin', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Horizontalsperre',
                    'Marke' => 'Tobolin',
                ],
            ],
            [
                'slug' => 'nachfullkanister-2-x-5-l-fur-horizontalsperre-injektionsflaschen',
                'name' => 'Nachfüllkanister (2 x 5 L) für Horizontalsperre Injektionsflaschen',
                'brand' => 'Tobolin',
                'category' => 'Horizontalsperre',
                'price' => '13,99 €',
                'priceCents' => 1399,
                'image' => 'https://www.tobolin.de/media/bb/f2/52/1691437811/03-07-10000-tobolin-horizontalsperre-mauerwerksabdichtung-kanister-trockene-mauer-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Horizontalsperre',
                'excerpt' => 'Schutz gegen kapillar aufsteigende Feuchtigkeit im Mauerwerk.',
                'description' => 'Nachfüllkanister (2 x 5 L) für Horizontalsperre Injektionsflaschen – Originalprodukt aus dem Tobolin-Shopbereich „Horizontalsperre“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Horizontalsperre', 'Marke Tobolin', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Horizontalsperre',
                    'Marke' => 'Tobolin',
                ],
            ],
            [
                'slug' => 'spezialgrundierung-vorbehandlung-fur-negativabdichtung',
                'name' => 'Spezialgrundierung – Vorbehandlung für Negativabdichtung',
                'brand' => 'Tobolin',
                'category' => 'Innenabdichtung',
                'price' => '59,90 €',
                'priceCents' => 5990,
                'image' => 'https://www.tobolin.de/media/ef/0f/d6/1754295732/de-produktbild-03-29.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Innenabdichtung',
                'excerpt' => 'Abdichtung und Sanierung von Wänden von innen.',
                'description' => 'Spezialgrundierung – Vorbehandlung für Negativabdichtung – Originalprodukt aus dem Tobolin-Shopbereich „Innenabdichtung“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Innenabdichtung', 'Marke Tobolin', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Innenabdichtung',
                    'Marke' => 'Tobolin',
                ],
            ],
            [
                'slug' => 'sanierputz-20-kg',
                'name' => 'Sanierputz 20 kg',
                'brand' => 'Tobolin',
                'category' => 'Innenabdichtung',
                'price' => '29,90 €',
                'priceCents' => 2990,
                'image' => 'https://www.tobolin.de/media/26/43/e2/1754295868/de-produktbild-mockup-03-35-20000.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Innenabdichtung',
                'excerpt' => 'Abdichtung und Sanierung von Wänden von innen.',
                'description' => 'Sanierputz 20 kg – Originalprodukt aus dem Tobolin-Shopbereich „Innenabdichtung“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Innenabdichtung', 'Marke Tobolin', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Innenabdichtung',
                    'Marke' => 'Tobolin',
                ],
            ],
            [
                'slug' => 'sperrputz-25-kg',
                'name' => 'Sperrputz 25 kg',
                'brand' => 'Tobolin',
                'category' => 'Innenabdichtung',
                'price' => '39,90 €',
                'priceCents' => 3990,
                'image' => 'https://www.tobolin.de/media/06/dc/43/1754295764/de-produktbild-mockup-03-31.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Innenabdichtung',
                'excerpt' => 'Abdichtung und Sanierung von Wänden von innen.',
                'description' => 'Sperrputz 25 kg – Originalprodukt aus dem Tobolin-Shopbereich „Innenabdichtung“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Innenabdichtung', 'Marke Tobolin', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Innenabdichtung',
                    'Marke' => 'Tobolin',
                ],
            ],
            [
                'slug' => 'feuchtigkeitsmessgerat-tobometer-hy',
                'name' => 'Feuchtigkeitsmessgerät TOBOMETER HY',
                'brand' => 'Tobolin',
                'category' => 'Feuchtemessung',
                'price' => '74,90 €',
                'priceCents' => 7490,
                'image' => 'https://www.tobolin.de/media/5e/a5/cd/1691437811/03-07-00050-feuchtigkeitsmessgeraet-tobometer-hy-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Feuchtemessung',
                'excerpt' => 'Feuchtigkeit in Wänden und Baustoffen messen und kontrollieren.',
                'description' => 'Feuchtigkeitsmessgerät TOBOMETER HY – Originalprodukt aus dem Tobolin-Shopbereich „Feuchtemessung“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Feuchtemessung', 'Marke Tobolin', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Feuchtemessung',
                    'Marke' => 'Tobolin',
                ],
            ],
            [
                'slug' => 'schutzhulle-fur-tobometer-hy',
                'name' => 'Schutzhülle für TOBOMETER HY',
                'brand' => 'Tobolin',
                'category' => 'Feuchtemessung',
                'price' => '17,90 €',
                'priceCents' => 1790,
                'image' => 'https://www.tobolin.de/media/42/20/b3/1754462935/03-07-00051-schuetzhuelle-fuer-tobometer-hy-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Feuchtemessung',
                'excerpt' => 'Feuchtigkeit in Wänden und Baustoffen messen und kontrollieren.',
                'description' => 'Schutzhülle für TOBOMETER HY – Originalprodukt aus dem Tobolin-Shopbereich „Feuchtemessung“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Feuchtemessung', 'Marke Tobolin', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Feuchtemessung',
                    'Marke' => 'Tobolin',
                ],
            ],
            [
                'slug' => 'rostfleckenentferner-250-ml',
                'name' => 'Rostfleckenentferner 250 mL',
                'brand' => 'Tobolin',
                'category' => 'Pflasterpflege',
                'price' => '19,90 €',
                'priceCents' => 1990,
                'image' => 'https://www.tobolin.de/media/df/1a/b5/1772710936/03-39-00250-tobolin-rostfleckenentferner-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Pflasterpflege',
                'excerpt' => 'Reinigung und Pflege für Pflaster, Steinflächen und Fugen.',
                'description' => 'Rostfleckenentferner 250 mL – Originalprodukt aus dem Tobolin-Shopbereich „Pflasterpflege“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Pflasterpflege', 'Marke Tobolin', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Pflasterpflege',
                    'Marke' => 'Tobolin',
                ],
            ],
            [
                'slug' => 'steinreiniger-hp-5000-ml',
                'name' => 'Steinreiniger HP 5000 mL',
                'brand' => 'Tobolin',
                'category' => 'Pflasterpflege',
                'price' => '9,98 €',
                'priceCents' => 998,
                'image' => 'https://www.tobolin.de/media/40/4e/1e/1775822929/de-produktbild-mockup-03-41-05000-01.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Pflasterpflege',
                'excerpt' => 'Reinigung und Pflege für Pflaster, Steinflächen und Fugen.',
                'description' => 'Steinreiniger HP 5000 mL – Originalprodukt aus dem Tobolin-Shopbereich „Pflasterpflege“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Pflasterpflege', 'Marke Tobolin', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Pflasterpflege',
                    'Marke' => 'Tobolin',
                ],
            ],
            [
                'slug' => 'steinreiniger-hp-steinschutz-hp-set',
                'name' => 'Steinreiniger HP & Steinschutz HP Set',
                'brand' => 'Tobolin',
                'category' => 'Pflasterpflege',
                'price' => '6,49 €',
                'priceCents' => 649,
                'image' => 'https://www.tobolin.de/media/5c/eb/b3/1778224992/produktbild-steinreiniger-steinschutz-bundle-002.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Pflasterpflege',
                'excerpt' => 'Reinigung und Pflege für Pflaster, Steinflächen und Fugen.',
                'description' => 'Steinreiniger HP & Steinschutz HP Set – Originalprodukt aus dem Tobolin-Shopbereich „Pflasterpflege“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Pflasterpflege', 'Marke Tobolin', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Pflasterpflege',
                    'Marke' => 'Tobolin',
                ],
            ],
            [
                'slug' => 'schraubwinkel-mit-gewinde',
                'name' => 'Schraubwinkel mit Gewinde',
                'brand' => 'Tobolin',
                'category' => 'Zubehör',
                'price' => '2,90 €',
                'priceCents' => 290,
                'image' => 'https://www.tobolin.de/media/a6/e6/b3/1754465185/int-produktfoto-03-07-00019.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Zubehör',
                'excerpt' => 'Zubehör für die Tobolin-Systemlösungen.',
                'description' => 'Schraubwinkel mit Gewinde – Originalprodukt aus dem Tobolin-Shopbereich „Zubehör“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Zubehör', 'Marke Tobolin', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Zubehör',
                    'Marke' => 'Tobolin',
                ],
            ],
            [
                'slug' => 'auslauftulle-mit-gewinde',
                'name' => 'Auslauftülle mit Gewinde',
                'brand' => 'Tobolin',
                'category' => 'Zubehör',
                'price' => '2,90 €',
                'priceCents' => 290,
                'image' => 'https://www.tobolin.de/media/28/f3/d6/1776689138/injektionsaufsaatz.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Zubehör',
                'excerpt' => 'Zubehör für die Tobolin-Systemlösungen.',
                'description' => 'Auslauftülle mit Gewinde – Originalprodukt aus dem Tobolin-Shopbereich „Zubehör“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Zubehör', 'Marke Tobolin', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Zubehör',
                    'Marke' => 'Tobolin',
                ],
            ],
            [
                'slug' => 'tobostick-kapillarstab-10-mm-x-160-cm',
                'name' => 'Tobostick Kapillarstab Ø 10 mm x 160 cm',
                'brand' => 'Tobolin',
                'category' => 'Zubehör',
                'price' => '3,16 €',
                'priceCents' => 316,
                'image' => 'https://www.tobolin.de/media/39/f7/ff/1691437808/03-07-00014-tobo-stick-horizontalsperre-glasfaser-1.webp',
                'deliveryTime' => '2–5 Tage',
                'badge' => 'Zubehör',
                'excerpt' => 'Zubehör für die Tobolin-Systemlösungen.',
                'description' => 'Tobostick Kapillarstab Ø 10 mm x 160 cm – Originalprodukt aus dem Tobolin-Shopbereich „Zubehör“. Name, Preis und Bild stammen aus dem Live-Shop.',
                'highlights' => ['Shopbereich Zubehör', 'Marke Tobolin', 'Live-Shopdaten als Platzhalter angebunden'],
                'specifications' => [
                    'Kategorie' => 'Zubehör',
                    'Marke' => 'Tobolin',
                ],
            ],
        ];
    }
}
